FitnessCenter.Web/Models/Appointment/AppointmentViewModel.cs
namespace FitnessCenter.Web.Models.Appointment
{
    public class AppointmentViewModel
    {
        public int AppointmentID { get; set; }
        public string ClientID{ get; set; }
        public string TrainerID { get; set; }
        public DateTime AppointmentDate { get; set; }
        public string DurationInMinutes { get; set; }
        public string Notes { get; set; }
    }

}

FitnessCenter.Web/Models/Customers/CustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FitnessCenter.Web.Models.Customers
{
    public class CustomerViewModel
    {
        [Required(ErrorMessage = "La identificación es requerida.")]
        [Display(Name = "Identificación")]
        public int Identificacion { get; set; }

        [Required(ErrorMessage = "El nombre es requerido.")]
        [Display(Name = "Nombre")]
        [StringLength(50, ErrorMessage = "El nombre no puede exceder los 50 caracteres.")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El primer apellido es requerido.")]
        [Display(Name = "Primer Apellido")]
        [StringLength(50, ErrorMessage = "El primer apellido no puede exceder los 50 caracteres.")]
        public string PrimerApellido { get; set; }

        [Required(ErrorMessage = "El segundo apellido es requerido.")]
        [Display(Name = "Segundo Apellido")]
        [StringLength(50, ErrorMessage = "El segundo apellido no puede exceder los 50 caracteres.")]
        public string SegundoApellido { get; set; }

        [Required(ErrorMessage = "El teléfono es requerido.")]
        [Display(Name = "Teléfono")]
        [StringLength(50, ErrorMessage = "El teléfono no puede exceder los 50 caracteres.")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "El correo electrónico es requerido.")]
        [Display(Name = "Correo Electrónico")]
        [EmailAddress(ErrorMessage = "El correo electrónico no es válido.")]
        [StringLength(100, ErrorMessage = "El correo electrónico no puede exceder los 100 caracteres.")]
        public string Email { get; set; }
    }
}

FitnessCenter.Web/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenter.Web.Controllers
{
    public class AppointmentController : Controller
    {

        [HttpGet]
        public IActionResult ListAppointments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateAppointment()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UpdateAppointment()
        {
            return View();
        }
    }
}

FitnessCenter.Web/Controllers/CustomersController.cs
using FitnessCenter.Web.Models;
using Microsoft.AspNetCore.Mvc;
using FitnessCenter.DTO;
using FitnessCenter.Core;

namespace FitnessCenter.Web.Controllers
{
    public class CustomersController : Controller
    {

        [HttpGet]
        public IActionResult Home()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Classes()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Appointments()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Progress()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Trainings()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ListCustomers()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateCustomers()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UpdateCustomers()
        {
            return View();
        }

    }
}

FitnessCenter.Web/Controllers/HomeController.cs
using FitnessCenter.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FitnessCenter.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FitnessCenter.Web/Controllers/LandingPageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenterSolution.Web.Controllers
{
    public class LandingPageController : Controller
    {
        // GET: AccountController
        public IActionResult LandingPage()
        {
            return View(); 
        }


    }
}

FitnessCenter.Web/Controllers/ReceptionistController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenter.Web.Controllers
{
    public class ReceptionistController : Controller
    {
        [HttpGet]
        public IActionResult HomeReceptionist()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Profile()
        {
            return View();
        }
    }
}

FitnessCenter.Web/Controllers/RoutineController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenter.Web.Controllers
{
    public class RoutineController : Controller
    {
        [HttpGet]
        public IActionResult CreateRoutine()
        {
            return View();
        }
        [HttpGet]
        public IActionResult ListRoutines()
        {
            return View();
        }
    }
}

FitnessCenter.Web/Controllers/TrainerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenter.Web.Controllers
{
    public class TrainerController : Controller
    {
        [HttpGet]
        public IActionResult ListGroupClasses()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateGroupClasses()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UpdateGroupClasses()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateAppointment()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateMeasurement()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Home()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateExercise()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateEquipment()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateExerciseType()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Profile()
        {
            return View();
        }
    }
}

FitnessCenter.Web/Views/Customers/Appointments.cshtml
@{
    ViewData["Title"] = "Appointments";
    Layout = null; // No usar el layout predeterminado
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Citas de Medicion</title>
    <link rel="stylesheet" type="text/css" href="~/css/Customers/Home.css" />
    <link rel="stylesheet" type="text/css" href="~/css/Customers/Appointments.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">

</head>

<body class="fondo">
    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" asp-controller="Customers" asp-action="Home">
            <img src="../Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Home">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Routine" asp-action="ListRoutines">Rutinas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Appointments">Citas de medición</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Classes">Clases</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Trainings">Entrenamientos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Progress">Progreso</a>
                </li>

                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Account" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a id="logoutButton" class="nav-link">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <h2 class="textoBlanco">Citas de medición</h2>
    <div class="container mt-5">
      
    <div id="calendar-container">
        <div id="calendar"></div>
        <div id="appointment-details">
            <h3>Detalles de la Cita</h3>
            <h5 id="title"></h5>
            <p id="hora"></p>  
        </div>
       </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/locales/es.js"></script>
    <script src="~/js/Customers/Appointment.js"></script>
    <script src="~/js/site.js"></script>


</body>
</html>

FitnessCenter.Web/Views/Customers/Classes.cshtml
@{
    ViewData["Title"] = "Classes";
    Layout = null; // No usar el layout predeterminado
}
   
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clases Grupales</title>
    <link rel="stylesheet" type="text/css" href="~/css/Customers/Home.css" />
    <link rel="stylesheet" type="text/css" href="~/css/Customers/Classes.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
   
</head>
<body class="fondo">
    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" asp-controller="Customers" asp-action="Home">
            <img src="../Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Home">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Routine" asp-action="ListRoutines">Rutinas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Appointments">Citas de medición</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Classes">Clases</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Trainings">Entrenamientos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="Progress">Progreso</a>
                </li>

                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Account" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a id="logoutButton" class="nav-link">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <h2 class="mb-5 titulo">Clases Grupales</h2>
    <div class="container mt-5">
       
        <div class="row" id="clasesGrupales">
           
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/Customers/Classes.js"></script>
    <script src="~/js/site.js"></script>
</body>
</html>

FitnessCenter.Web/Views/Customers/CreateCustomers.cshtml
@model FitnessCenter.Web.Models.Customers.CustomerViewModel;

@{
    ViewData["Title"] = "Registrar Clientes";
    Layout = null; // No usar el layout predeterminado
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/Customers/CreateCustomers.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" href="@Url.Action("HomeReceptionist", "Receptionist")">
            <img src="../Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Receptionist" asp-action="HomeReceptionist">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Appointment" asp-action="ListAppointments">Citas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="ListCustomers">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Trainer" asp-action="ListGroupClasses">Clases Grupales</a>
                </li>
                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Receptionist" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="LandingPage" asp-action="LandingPage">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        <div class="form-container">
            <form id="createCustomerForm" class="form-group">
                <div class="titulo">
                    <h2>Registrar Nuevo Cliente</h2>
                </div>
                <div class="inputContainer">
                    <div class="inputgroup">
                        <div class="form-group">
                            <label for="Nombre">Nombre Completo</label>
                            <input class="form-control" id="Nombre" name="Nombre">
                        </div>
                        <div class="form-group">
                            <label for="Telefono">Teléfono</label>
                            <input class="form-control" id="Telefono" name="Telefono">
                        </div>
                    </div>
                    <div class="inputgroup">
                        <div class="form-group">
                            <label for="Identificacion">Cédula</label>
                            <input class="form-control" id="Identificacion" name="Identificacion">
                        </div>
                        <div class="form-group">
                            <label for="Email">Correo Electrónico</label>
                            <input class="form-control" id="Email" name="Email">
                        </div>
                    </div>
                </div>
                <div class="buttons">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="@Url.Action("HomeReceptionist", "Receptionist")" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/Customers/CreateCustomers.js"></script>
    <script src="~/js/site.js"></script>

</body>

</html>

FitnessCenter.Web/Views/Customers/ListCustomers.cshtml
@{
    ViewData["Title"] = "Lista de Clientes";
    Layout = null; // No usar el layout predeterminado
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Customers/ListCustomers.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" href="@Url.Action("HomeReceptionist", "Receptionist")">
            <img src="../Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Receptionist" asp-action="HomeReceptionist">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Appointment" asp-action="ListAppointments">Citas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="ListCustomers">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Trainer" asp-action="ListGroupClasses">Clases Grupales</a>
                </li>
                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Receptionist" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="LandingPage" asp-action="LandingPage">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4 table-container">
        <div class="customerContainer">
            <div class="main-content">
                <h2 class="text-center text-white">Lista de Clientes</h2>
                <table id="customerTable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Teléfono</th>
                            <th>Correo Electrónico</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Aquí se llenarán los datos dinámicamente -->
                    </tbody>
                </table>
            </div>
        </div>
        <div class="buttons">
            <button onclick="window.location.href='@Url.Action("CreateCustomers", "Customers")'" class="btn btn-primary">Registrar Cliente</button>
        </div>
    </div>
    <script src="https://cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/Customers/ListCustomers.js"></script>
    <script src="~/js/site.js"></script>
</body>

</html>

FitnessCenter.Web/Views/Customers/UpdateCustomers.cshtml
@model FitnessCenter.Web.Models.Appointment.AppointmentViewModel;

@{
    ViewData["Title"] = "Editar Clientes";
    Layout = null; // No usar el layout predeterminado
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/Customers/UpdateCustomers.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" href="@Url.Action("HomeReceptionist", "Receptionist")">
            <img src="~/Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Receptionist" asp-action="HomeReceptionist">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Appointment" asp-action="ListAppointments">Citas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="ListCustomers">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Trainer" asp-action="ListGroupClasses">Clases Grupales</a>
                </li>
                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Receptionist" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="LandingPage" asp-action="LandingPage">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        <div class="form-container">
            <form id="createCustomerForm" class="form-group">
                <div class="titulo">
                    <h2>Editar Cliente</h2>
                </div>
                <div class="idCustomer">
                    <p id="customerID">ID: </p>
                </div>
                <input type="hidden" id="customerID" name="customerID" />
                <div class="inputContainer">
                    <div class="inputgroup">
                        <div class="form-group">
                            <label for="Nombre">Nombre Completo</label>
                            <input type="text" class="form-control" id="Nombre" name="Nombre" readonly>
                            <input type="hidden" id="Nombre" name="Nombre">
                        </div>
                        <div class="form-group">
                            <label for="Telefono">Teléfono</label>
                            <input class="form-control" id="Telefono" name="Telefono">
                        </div>
                    </div>
                    <div class="inputgroup">
                        <div class="form-group">
                            <label for="Identificacion">Cédula</label>
                            <input type="text" class="form-control" id="Identificacion" name="Identificacion" readonly>
                            <input type="hidden" id="Identificacion" name="Identificacion">
                        </div>
                        <div class="form-group">
                            <label for="Email">Correo Electrónico</label>
                            <input class="form-control" id="Email" name="Email">
                        </div>
                    </div>
                </div>
                <div class="buttons">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="@Url.Action("HomeReceptionist", "Receptionist")" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/Customers/UpdateCustomers.js"></script>
    <script src="~/js/site.js"></script>

</body>

</html>