FitnessCenter.Web/Models/Payment/PaymentViewModel.cs
namespace FitnessCenter.Web.Models.Payment
{
    public class PaymentViewModel
    {
    }
}

FitnessCenter.Web/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenter.Web.Controllers
{
    public class AppointmentController : Controller
    {

        [HttpGet]
        public IActionResult ListAppointments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateAppointment()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UpdateAppointment()
        {
            return View();
        }
    }
}

FitnessCenter.Web/Controllers/CustomersController.cs
using FitnessCenter.Web.Models;
using Microsoft.AspNetCore.Mvc;
using FitnessCenter.DTO;
using FitnessCenter.Core;

namespace FitnessCenter.Web.Controllers
{
    public class CustomersController : Controller
    {

        [HttpGet]
        public IActionResult Home()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Classes()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Appointments()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Progress()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Trainings()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ListCustomers()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateCustomers()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UpdateCustomers()
        {
            return View();
        }

    }
}

FitnessCenter.Web/Controllers/LandingPageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenterSolution.Web.Controllers
{
    public class LandingPageController : Controller
    {
        // GET: AccountController
        public IActionResult LandingPage()
        {
            return View(); 
        }


    }
}

FitnessCenter.Web/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenter.Web.Controllers
{
    public class PaymentController : Controller
    {
        [HttpGet]
        public IActionResult CreatePayments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ListPayments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult PaymentDetails()
        {
            return View();
        }
    }
}

FitnessCenter.Web/Controllers/TrainerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCenter.Web.Controllers
{
    public class TrainerController : Controller
    {
        [HttpGet]
        public IActionResult ListGroupClasses()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateGroupClasses()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UpdateGroupClasses()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateAppointment()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateMeasurement()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Home()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateExercise()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateEquipment()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateExerciseType()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Profile()
        {
            return View();
        }
    }
}

FitnessCenter.Web/Views/Payment/CreatePayments.cshtml
@model FitnessCenter.Web.Models.Payment.PaymentViewModel;

@{
    ViewData["Title"] = "Registrar Pagos";
    Layout = null; // No usar el layout predeterminado
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/Payment/CreatePayment.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" href="@Url.Action("HomeReceptionist", "Receptionist")">
            <img src="../Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Receptionist" asp-action="HomeReceptionist">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Appointment" asp-action="ListAppointments">Citas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="ListCustomers">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Trainer" asp-action="ListGroupClasses">Clases Grupales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Payment" asp-action="ListPayments">Pagos</a>
                </li>
                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Account" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="LandingPage" asp-action="LandingPage">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        <div class="form-container">
            <form id="createPaymentForm" class="form-group">
                <div class="titulo">
                    <h2>Registrar Nuevo Pago</h2>
                </div>
                <div class="inputContainer">
                    <div class="inputgroup">
                        <div class="form-group">
                            <label for="Cliente">Cliente</label>
                            <select class="form-control" id="Cliente" name="ClienteId">
                                <!-- Opciones de cliente -->
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="FechaHora">Fecha y Hora</label>
                            <input type="datetime-local" class="form-control" id="FechaHora" name="FechaHora">
                        </div>
                    </div>
                    <div class="inputgroup">
                        <div class="form-group">
                            <label for="MetodoPago">Método de Pago</label>
                            <select class="form-control" id="MetodoPago" name="MetodoPago">
                                <!-- Opciones serán agregadas aquí -->
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="Monto">Monto</label>
                            <input class="form-control" id="Monto" name="Monto">
                        </div>
                    </div>
                </div>
                <div class="buttons">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="@Url.Action("HomeReceptionist", "Receptionist")" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/Payment/CreatePayment.js"></script>
    <script src="~/js/site.js"></script>

</body>

</html>

FitnessCenter.Web/Views/Payment/ListPayments.cshtml
@{
    ViewData["Title"] = "Lista de Pagos";
    Layout = null; // No usar el layout predeterminado
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Payment/ListPayment.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" href="@Url.Action("HomeReceptionist", "Receptionist")">
            <img src="../Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Receptionist" asp-action="HomeReceptionist">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Appointment" asp-action="ListAppointments">Citas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="ListCustomers">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Trainer" asp-action="ListGroupClasses">Clases Grupales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Payment" asp-action="ListPayments">Pagos</a>
                </li>
                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Account" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="LandingPage" asp-action="LandingPage">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4 table-container">
        <div class="paymentContainer">
            <div class="main-content">
                <h2 class="text-center text-white">Pagos</h2>
                <table id="paymentTable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Cliente</th>
                            <th>Monto</th>
                            <th>Método de Pago</th>
                            <th>Fecha de Pago</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Aquí se llenarán los datos dinámicamente -->
                    </tbody>
                </table>
            </div>
        </div>
        <div class="buttons">
            <button onclick="window.location.href='@Url.Action("CreatePayments", "Payment")'" class="btn btn-primary">Registrar Pago</button>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/Payment/ListPayment.js"></script>
    <script src="~/js/site.js"></script>
</body>

</html>

FitnessCenter.Web/Views/Payment/PaymentDetails.cshtml
@{
    ViewData["Title"] = "Resumen de Citas del Dia";
    Layout = null; // No usar el layout predeterminado
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Payment/PaymentDetails.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-custom fondoNav">
        <a class="navbar-brand" href="@Url.Action("HomeReceptionist", "Receptionist")">
            <img src="../Images/login-logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Receptionist" asp-action="HomeReceptionist">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Appointment" asp-action="ListAppointments">Citas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customers" asp-action="ListCustomers">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Trainer" asp-action="ListGroupClasses">Clases Grupales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Payment" asp-action="ListPayments">Pagos</a>
                </li>
                <li class="nav-item">
                    <a class="profile-icon nav-link" asp-controller="Account" asp-action="Profile">
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="LandingPage" asp-action="LandingPage">
                        <i class="fas fa-sign-out-alt"></i> <!-- Icono de salir -->
                    </a>
                </li>
            </ul>
        </div>
    </nav>

        <header class="titulo">
            <h1>Detalles de Pago</h1>
        </header>

    <div class="container">
        <section class="info-cliente">
            <h2>Información del cliente</h2>
            <p><strong>Nombre completo:</strong> <span id="nombre-completo"></span></p>
            <p><strong>Cédula:</strong> <span id="cedula"></span></p>
            <p><strong>Teléfono:</strong> <span id="telefono"></span></p>
            <p><strong>Email:</strong> <span id="email"></span></p>
            <p><strong>Estado:</strong> <span id="estado"></span></p>
        </section>

        <section class="info-pago">
            <h2>Información del pago</h2>
            <p><strong>Fecha de Pago:</strong> <span id="fecha-pago"></span></p>
            <p><strong>Método de Pago:</strong> <span id="metodo-pago"></span></p>
            <p><strong>Monto:</strong> <span id="monto"></span></p>
        </section>

    </div>
    <div class="buttons">
        <button onclick="window.location.href='@Url.Action("ListPayments", "Payment")'"  id="atras-btn" class="btn btn-primary">Atrás</button>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/Payment/PaymentDetails.js"></script>
    <script src="~/js/site.js"></script>
</body>
</html>